repos:
  - repo: https://github.com/ambv/black
    rev: 21.12b0
    hooks:
      - id: black

  - repo: https://github.com/timothycrosley/isort
    rev: 5.10.1
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/(toml-test|toml-spec-tests)/.*
      - id: end-of-file-fixer
        exclude: ^tests/(toml-test|toml-spec-tests)/.*
      - id: debug-statements
