[tool.poetry]
name = "tomlkit"
version = "0.1.0"
description = "Style preserving TOML parser"
authors = ["Sébastien Eustace <sebastien@eustace.io>"]
license = "MIT"

readme = "README.md"

homepage = "https://github.com/sdispater/tomlkit"
repository = "https://github.com/sdispater/tomlkit"

[tool.poetry.dependencies]
python = "~2.7 || ^3.4"

[tool.poetry.dev-dependencies]
pytest = "^3.6"
pytest-cov = "^2.5"
black = { version = "^18.6b4", python = "^3.6" }
pre-commit = "^1.10"
